

### 등록
POST http://localhost:8080/api/v1/job-advertisements/3
Content-Type: application/json

{

  "position":"주니어 백엔드 개발자",
  "reward":500000,
  "content":"원티드랩에서 백엔드 주니어 개발자를 채용합니다. 자격요건은..",
  "skill":"Spring",
  "nation": "한국",
  "region": "서울"
}





### 수정
PUT http://localhost:8080/api/v1/job-advertisements/3/75
Content-Type: application/json

{

  "position":"백엔드 주니어 개efefeㄹㄷㅈㄹㅈㄷ발자",
  "reward":10009999,
  "content":"채용내용",
  "skill":"Python",
  "nation": "미국",
  "region": "뉴욕"
}




### 삭제
DELETE http://localhost:8080/api/v1/job-advertisements
Content-Type: application/json

{
  "job_advertisement_id": 77
}



### 목록보기
GET http://localhost:8080/api/v1/job-advertisements



### 검색
GET http://localhost:8080/api/v1/job-advertisements/search?keyword=카



### 상세보기
GET http://localhost:8080/api/v1/job-advertisements/detail/81





###

